import Phaser from 'phaser'

import { TitleScreen, GameOver, YouWin, Game } from '../consts/SceneKeys'

import WebFontFile from './WebFontFile'

export default class Preload extends Phaser.Scene
{
    
        preload()
        {
            this.load.image("WesternWorld", "./assets/WesternWorld.png")
            this.load.image("FloorBoards", "./assets/FloorBoards.png")
            this.load.image("WagonD", "./sprites/WagonD.png")
            this.load.image("WagonDR", "./sprites/WagonDR.png")
            this.load.image("WagonDL", "./sprites/WagonDL.png")
            this.load.image("WagonU", "./sprites/WagonU.png")
            this.load.image("WagonUR", "./sprites/WagonUR.png")
            this.load.image("WagonUL", "./sprites/WagonUL.png")
            this.load.image("WagonR", "./sprites/WagonR.png")
            this.load.image("WagonL", "./sprites/WagonL.png")
            this.load.image("ArrowD", "./sprites/ArrowD.png")
            this.load.image("ArrowDR", "./sprites/ArrowDR.png")
            this.load.image("ArrowDL", "./sprites/ArrowDL.png")
            this.load.image("ArrowU", "./sprites/ArrowU.png")
            this.load.image("ArrowUR", "./sprites/ArrowUR.png")
            this.load.image("ArrowUL", "./sprites/ArrowUL.png")
            this.load.image("ArrowR", "./sprites/ArrowR.png")
            this.load.image("ArrowL", "./sprites/ArrowL.png")
            this.load.image("Person", "./sprites/Person.png")
            this.load.image("Supplies", "./sprites/Supplies.png")
            this.load.image("Test", "./sprites/download.png")
            this.load.image("A1", "./squares/A1.png")
            this.load.image("A2", "./squares/A2.png")
            this.load.image("A3", "./squares/A3.png")
            this.load.image("A4", "./squares/A4.png")
            this.load.image("A5", "./squares/A5.png")
            this.load.image("A6", "./squares/A6.png")
            this.load.image("A7", "./squares/A7.png")
            this.load.image("A8", "./squares/A8.png")
            this.load.image("A9", "./squares/A9.png")
            this.load.image("A10", "./squares/A10.png")
            this.load.image("A11", "./squares/A11.png")
            this.load.image("A12", "./squares/A12.png")
            this.load.image("A13", "./squares/A13.png")
            this.load.image("A14", "./squares/A14.png")
            this.load.image("A15", "./squares/A15.png")
            this.load.image("B1", "./squares/B1.png")
            this.load.image("B2", "./squares/B2.png")
            this.load.image("B3", "./squares/B3.png")
            this.load.image("B4", "./squares/B4.png")
            this.load.image("B5", "./squares/B5.png")
            this.load.image("B6", "./squares/B6.png")
            this.load.image("B7", "./squares/B7.png")
            this.load.image("B8", "./squares/B8.png")
            this.load.image("B9", "./squares/B9.png")
            this.load.image("B10", "./squares/B10.png")
            this.load.image("B11", "./squares/B11.png")
            this.load.image("B12", "./squares/B12.png")
            this.load.image("B13", "./squares/B13.png")
            this.load.image("B14", "./squares/B14.png")
            this.load.image("B15", "./squares/B15.png")
            this.load.image("C1", "./squares/C1.png")
            this.load.image("C2", "./squares/C2.png")
            this.load.image("C3", "./squares/C3.png")
            this.load.image("C4", "./squares/C4.png")
            this.load.image("C5", "./squares/C5.png")
            this.load.image("C6", "./squares/C6.png")
            this.load.image("C7", "./squares/C7.png")
            this.load.image("C8", "./squares/C8.png")
            this.load.image("C9", "./squares/C9.png")
            this.load.image("C10", "./squares/C10.png")
            this.load.image("C11", "./squares/C11.png")
            this.load.image("C12", "./squares/C12.png")
            this.load.image("C13", "./squares/C13.png")
            this.load.image("C14", "./squares/C14.png")
            this.load.image("C15", "./squares/C15.png")
            this.load.image("D1", "./squares/D1.png")
            this.load.image("D2", "./squares/D2.png")
            this.load.image("D3", "./squares/D3.png")
            this.load.image("D4", "./squares/D4.png")
            this.load.image("D5", "./squares/D5.png")
            this.load.image("D6", "./squares/D6.png")
            this.load.image("D7", "./squares/D7.png")
            this.load.image("D8", "./squares/D8.png")
            this.load.image("D9", "./squares/D9.png")
            this.load.image("D10", "./squares/D10.png")
            this.load.image("D11", "./squares/D11.png")
            this.load.image("D12", "./squares/D12.png")
            this.load.image("D13", "./squares/D13.png")
            this.load.image("D14", "./squares/D14.png")
            this.load.image("D15", "./squares/D15.png")
            this.load.image("E1", "./squares/E1.png")
            this.load.image("E2", "./squares/E2.png")
            this.load.image("E3", "./squares/E3.png")
            this.load.image("E4", "./squares/E4.png")
            this.load.image("E5", "./squares/E5.png")
            this.load.image("E6", "./squares/E6.png")
            this.load.image("E7", "./squares/E7.png")
            this.load.image("E8", "./squares/E8.png")
            this.load.image("E9", "./squares/E9.png")
            this.load.image("E10", "./squares/E10.png")
            this.load.image("E11", "./squares/E11.png")
            this.load.image("E12", "./squares/E12.png")
            this.load.image("E13", "./squares/E13.png")
            this.load.image("E14", "./squares/E14.png")
            this.load.image("E15", "./squares/E15.png")
            this.load.image("F1", "./squares/F1.png")
            this.load.image("F2", "./squares/F2.png")
            this.load.image("F3", "./squares/F3.png")
            this.load.image("F4", "./squares/F4.png")
            this.load.image("F5", "./squares/F5.png")
            this.load.image("F6", "./squares/F6.png")
            this.load.image("F7", "./squares/F7.png")
            this.load.image("F8", "./squares/F8.png")
            this.load.image("F9", "./squares/F9.png")
            this.load.image("F10", "./squares/F10.png")
            this.load.image("F11", "./squares/F11.png")
            this.load.image("F12", "./squares/F12.png")
            this.load.image("F13", "./squares/F13.png")
            this.load.image("F14", "./squares/F14.png")
            this.load.image("F15", "./squares/F15.png")
            this.load.image("G1", "./squares/G1.png")
            this.load.image("G2", "./squares/G2.png")
            this.load.image("G3", "./squares/G3.png")
            this.load.image("G4", "./squares/G4.png")
            this.load.image("G5", "./squares/G5.png")
            this.load.image("G6", "./squares/G6.png")
            this.load.image("G7", "./squares/G7.png")
            this.load.image("G8", "./squares/G8.png")
            this.load.image("G9", "./squares/G9.png")
            this.load.image("G10", "./squares/G10.png")
            this.load.image("G11", "./squares/G11.png")
            this.load.image("G12", "./squares/G12.png")
            this.load.image("G13", "./squares/G13.png")
            this.load.image("G14", "./squares/G14.png")
            this.load.image("G15", "./squares/G15.png")
            this.load.image("H1", "./squares/H1.png")
            this.load.image("H2", "./squares/H2.png")
            this.load.image("H3", "./squares/H3.png")
            this.load.image("H4", "./squares/H4.png")
            this.load.image("H5", "./squares/H5.png")
            this.load.image("H6", "./squares/H6.png")
            this.load.image("H7", "./squares/H7.png")
            this.load.image("H8", "./squares/H8.png")
            this.load.image("H9", "./squares/H9.png")
            this.load.image("H10", "./squares/H10.png")
            this.load.image("H11", "./squares/H11.png")
            this.load.image("H12", "./squares/H12.png")
            this.load.image("H13", "./squares/H13.png")
            this.load.image("H14", "./squares/H14.png")
            this.load.image("H15", "./squares/H15.png")
            this.load.image("I1", "./squares/I1.png")
            this.load.image("I2", "./squares/I2.png")
            this.load.image("I3", "./squares/I3.png")
            this.load.image("I4", "./squares/I4.png")
            this.load.image("I5", "./squares/I5.png")
            this.load.image("I6", "./squares/I6.png")
            this.load.image("I7", "./squares/I7.png")
            this.load.image("I8", "./squares/I8.png")
            this.load.image("I9", "./squares/I9.png")
            this.load.image("I10", "./squares/I10.png")
            this.load.image("I11", "./squares/I11.png")
            this.load.image("I12", "./squares/I12.png")
            this.load.image("I13", "./squares/I13.png")
            this.load.image("I14", "./squares/I14.png")
            this.load.image("I15", "./squares/I15.png")
            this.load.image("background", "./assets/background.png")
            this.load.image("textBox", "./assets/textBox.png")
            this.load.image("youWin", "./assets/youWin.jpg")
            this.load.image("gameOver", "./assets/gameOver.png")
            const fonts = new WebFontFile(this.load, 'Rye')
            this.load.addFile(fonts)
        }

        create()
        {
            this.scene.start(TitleScreen)
        }
}
